CREATE TABLE "Y24GROUP054"."PARENT" 
   (	"PARENT_ID" NUMBER CONSTRAINT "PARENT_ID_NN" NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(40), 
	"SURNAME" VARCHAR2(40), 
	"PARENT_TYPE" NUMBER, 
	 CONSTRAINT "PARENT_C_ID_PK" PRIMARY KEY ("PARENT_ID") ENABLE, 
	 CONSTRAINT "PARENT_TYP_FK" FOREIGN KEY ("PARENT_TYPE")
	  REFERENCES "Y24GROUP054"."PARENT_TYPE" ("PARENT_TYPE") ENABLE
   ) 

   COMMENT ON COLUMN "Y24GROUP054"."PARENT"."PARENT_ID" IS 'Primary key of PARENT table.';
   COMMENT ON COLUMN "Y24GROUP054"."PARENT"."FIRST_NAME" IS 'First name of PARENT';
   COMMENT ON COLUMN "Y24GROUP054"."PARENT"."SURNAME" IS 'Surname of PARENT';
   COMMENT ON COLUMN "Y24GROUP054"."PARENT"."PARENT_TYPE" IS 'PARENT table. Contains 25 rows. References with locations table.';
   COMMENT ON TABLE "Y24GROUP054"."PARENT" IS 'PARENT table. Contains 25 rows. References with locations table.';