ALTER TABLE "Y24GROUP054"."CHILD"
ADD (
    CONSTRAINT CHILD_PARENT_FK foreign key ("PARENT_ID") references "PARENT" ("PARENT_ID"),
    CONSTRAINT CHILD_WLIST_FK foreign key ("WAITLIST_ID") references "WAITLIST" ("WAITLIST_ID")
);