ALTER TABLE "Y24GROUP054"."CLASS_ACTIVITY"
ADD (
    CONSTRAINT CACT_CLASS_FK foreign key ("CLASS_ID") references "CLASS" ("CLASS_ID"),
    CONSTRAINT CACT_ACT_FK foreign key ("ACTIVITY_ID") references "ACTIVITY" ("ACTIVITY_ID")
);