ALTER TABLE "Y24GROUP054"."CLASS_ACTIVITY"
ADD (
    CONSTRAINT ACTIVITY_PK PRIMARY KEY ("CLASS_ID", "ACTIVITY_ID") ENABLE,
    CONSTRAINT CACT_CLASS_FK FOREIGN KEY ("CLASS_ID") references "CLASS" ("CLASS_ID"),
    CONSTRAINT CACT_ACT_FK FOREIGN KEY ("ACTIVITY_ID") references "ACTIVITY" ("ACTIVITY_ID")
);