ALTER TABLE "Y24GROUP054"."EMPLOYEE_QUALIFICATION"
ADD (
    CONSTRAINT QUAL_EMP_FK foreign key ("EMPLOYEE_ID") references "EMPLOYEE" ("EMPLOYEE_ID"),
    CONSTRAINT QUAL_QID_FK foreign key ("QUALIFICATION_ID") references "QUALIFICATION" ("QUALIFICATION_ID")
);