--header
CREATE TABLE "Y24GROUP054"."ACTIVITY" (
    "ACTIVITY_ID" INTEGER DEFAULT ACTIVITY_ID_SEQ.NEXTVAL
    CONSTRAINT ACTIVITY_ID_PK PRIMARY KEY ENABLE,
    "NAME" VARCHAR2(50) NOT NULL,
    "DESCRIPTION" VARCHAR2(50)
);
CREATE TABLE "Y24GROUP054"."CHILD_ATTENDANCE" (
    "ROLL_ID" INTEGER DEFAULT ROLL_ID_SEQ.NEXTVAL
        CONSTRAINT CHLD_ATTN_ID_PK PRIMARY KEY ENABLE,
    "CHILD_ID" INTEGER NOT NULL,
    "CLASS_ID" INTEGER NOT NULL,
    "ARRIVAL" DATE NOT NULL,
    "DEPARTURE" DATE NOT NULL
);
CREATE TABLE "Y24GROUP054"."CHILD_MEDICATION" (
    "RECORD_ID" INTEGER DEFAULT RECORD_ID_SEQ.NEXTVAL
        CONSTRAINT RECORD_ID_PK PRIMARY KEY ENABLE,
    "CHILD_ID" INTEGER NOT NULL,
    "MEDICATION_ID" INTEGER NOT NULL,
    "DOSAGE_MG" NUMBER(6, 2),
    "FREQUENCY" VARCHAR2(30),
    "DESCRIPTION" VARCHAR2(50)
);
CREATE TABLE "Y24GROUP054"."CHILD" (
    "CHILD_ID" INTEGER DEFAULT CHILD_ID_SEQ.NEXTVAL
        CONSTRAINT CHILD_ID_PK PRIMARY KEY ENABLE,
    "PARENT_ID" INTEGER NOT NULL,
    "WAITLIST_ID" INTEGER,
    "FIRST_NAME" VARCHAR2(20)
     CONSTRAINT CHLD_FIRST_NAME_NN NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(25)
     CONSTRAINT CHLD_LAST_NAME_NN NOT NULL ENABLE,
    "EMERGENCY_CONTACT" CONTACT,
    "CCS_PERCENTAGE" NUMBER(4, 4) DEFAULT 0,
    "DOB" DATE
);
CREATE TABLE "Y24GROUP054"."CLASS_ACTIVITY" (
    "CLASS_ID" INTEGER NOT NULL,
    "ACTIVITY_ID" INTEGER NOT NULL
);
CREATE TABLE "Y24GROUP054"."CLASS" (
    "CLASS_ID" INTEGER DEFAULT CLASS_ID_SEQ.NEXTVAL
        CONSTRAINT CLASS_ID_PK PRIMARY KEY ENABLE,
    "CLASS_NAME" VARCHAR(5),
    "ROOM_ID" INTEGER NOT NULL
);
CREATE TABLE "Y24GROUP054"."EMPLOYEE_ATTENDANCE" (
    "ROLL_ID" INTEGER DEFAULT ROLL_ID_SEQ.NEXTVAL
        CONSTRAINT EMP_ATTN_ID_PK PRIMARY KEY ENABLE,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "CLASS_ID" INTEGER NOT NULL,
    "ARRIVAL" DATE,
    "DEPARTURE" DATE
);
CREATE TABLE "Y24GROUP054"."EMPLOYEE_QUALIFICATION" (
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "QUALIFICATION_ID" INTEGER NOT NULL
);
CREATE TABLE "Y24GROUP054"."EMPLOYEE" (
    "EMPLOYEE_ID" INTEGER DEFAULT EMPLOYEE_ID_SEQ.NEXTVAL
        CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY ENABLE,
    "FIRST_NAME" VARCHAR2(20) CONSTRAINT EMP_FIRST_NAME_NN NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(25) CONSTRAINT EMP_LAST_NAME_NN NOT NULL ENABLE,
    "EMAIL" VARCHAR2(50) CONSTRAINT EMP_EMAIL_NN NOT NULL ENABLE,
    "CONTACT_NUMBER" VARCHAR2(20),
    "HIRE_DATE" DATE CONSTRAINT EMP_HIRE_DATE_NN NOT NULL ENABLE,
    "ADDRESS" ADDR_OBJ,
    "SALARY" NUMBER(8, 2)
    --"JOB_ID" VARCHAR2 (10) CONSTRAINT "EMP_JOB_NN" NOT NULL ENABLE,
);
CREATE TABLE "Y24GROUP054"."INVENTORY" (
    "INVENTORY_ID" INTEGER DEFAULT INVENTORY_ID_SEQ.NEXTVAL
        CONSTRAINT INVENTORY_ID_PK PRIMARY KEY ENABLE,
    "NAME" VARCHAR2(50) NOT NULL,
    "DESCRIPTION" VARCHAR2(50)
);
CREATE TABLE "Y24GROUP054"."MEDICATION" (
    "MEDICATION_ID" INTEGER DEFAULT MEDICATION_ID_SEQ.NEXTVAL
        CONSTRAINT MEDICATION_ID_PK PRIMARY KEY ENABLE,
    "MEDICATION_NAME" VARCHAR2(50)
);
CREATE TABLE "Y24GROUP054"."PARENT_TYPE" (
    "RECORD_ID" INTEGER CONSTRAINT PTYPE_ID_NN NOT NULL ENABLE,
    "TYPE_ID" NUMBER(1) NOT NULL,
    "TYPE_NAME" VARCHAR2(14) NOT NULL,
    "PARENT_ID" INTEGER NOT NULL,
    "EMPLOYEE_ID" INTEGER,
    "ZID" VARCHAR2(8),
    "LEAVE_DATE" DATE
);
CREATE TABLE "Y24GROUP054"."PARENT" (
    "PARENT_ID" INTEGER DEFAULT PARENT_ID_SEQ.NEXTVAL
        CONSTRAINT PARENT_ID_PK PRIMARY KEY ENABLE,
    "FIRST_NAME" VARCHAR2(20) CONSTRAINT PRNT_FIRST_NAME_NN NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(25) CONSTRAINT PRNT_LAST_NAME_NN NOT NULL ENABLE,
    "TYPE" NUMBER(1),
    "EMAIL" VARCHAR2(50) CONSTRAINT PRNT_EMAIL_NN NOT NULL ENABLE,
    "CONTACT_NUMBER" VARCHAR2(20),
    "ADDRESS" ADDR_OBJ
);
CREATE TABLE "Y24GROUP054"."PAYMENT" (
    "PAYMENT_ID" INTEGER DEFAULT PAYMENT_ID_SEQ.NEXTVAL
        CONSTRAINT PAYMENT_ID_PK PRIMARY KEY ENABLE,
    "CHILD_ID" INTEGER NOT NULL,
    "AMOUNT" NUMBER(8, 2),
    "DATE_ISSUE" DATE,
    "DATE_DUE" DATE,
    "STATUS" NVARCHAR2 (25)
);
CREATE TABLE "Y24GROUP054"."QUALIFICATION" (
    "QUALIFICATION_ID" INTEGER DEFAULT QUALIFICATION_ID_SEQ.NEXTVAL
        CONSTRAINT QUALIFICATION_ID_PK PRIMARY KEY ENABLE,
    "DESCRIPTION" VARCHAR2(100) CONSTRAINT QLF_DESC_NN NOT NULL ENABLE
);
CREATE TABLE "Y24GROUP054"."ROOM_INVENTORY" (
    "ROOM_ID" INTEGER NOT NULL ENABLE,
    "INVENTORY_ID" INTEGER NOT NULL
);
CREATE TABLE "Y24GROUP054"."ROOM" (
    "ROOM_ID" INTEGER DEFAULT ROOM_ID_SEQ.NEXTVAL
        CONSTRAINT ROOM_ID_PK PRIMARY KEY ENABLE,
    "NAME" VARCHAR2(25) NOT NULL,
    "LOCATION" VARCHAR2(50),
    "MAX_CAPACITY" NUMBER(3),
    "MIN_AGE" NUMBER(3),
    "MAX_AGE" NUMBER(3)
);
CREATE TABLE "Y24GROUP054"."WAITLIST" (
    "WAITLIST_ID" INTEGER DEFAULT WAITLIST_ID_SEQ.NEXTVAL
        CONSTRAINT WAITLIST_ID_PK PRIMARY KEY ENABLE,
    "DATE_ADDED" DATE
);
--footer
